export const mockGetShoppingList = {
  data: {
    list: {
      items: [
        {
          quantityNeeded: 3,
          unit: null,
          inCart: true,
          name: "banana",
          category: "PRODUCE",
          defaultUnit: "",
          id: "1r1ZAGJv8tXu7SSZPioP",
          catalogId: "q9Csu45w7Fyh5Cm0uMmT",
        },
        {
          quantityNeeded: 3,
          unit: null,
          inCart: null,
          name: "baking powder",
          category: "BAKING_SUPPLIES",
          defaultUnit: "",
          id: "5RK4r6Xw6b3xOct54T5b",
          catalogId: "7ron8dYBgH6zjBuYOpeT",
        },
        {
          quantityNeeded: 1,
          unit: "PACKAGE",
          inCart: true,
          name: "pretzels",
          category: "SNACKS",
          defaultUnit: null,
          id: "5zggpF5FTy4k991fcWND",
          catalogId: "gmNkPgPJEtJiWHMXVpu9",
        },
        {
          quantityNeeded: 12,
          unit: null,
          inCart: null,
          name: "bacon",
          category: "MEAT",
          defaultUnit: "",
          id: "8Xr7RqUgzqJv5LZ9db1w",
          catalogId: "f0QbQE2UFnutNHJ29rbF",
        },
        {
          quantityNeeded: 3,
          unit: null,
          inCart: null,
          name: "Parmesan cheese",
          category: "DAIRY",
          defaultUnit: "",
          id: "8bOchEZofB1dgSuYu8Mf",
          catalogId: "rSlQIDB2CZzvz4Klamug",
        },
        {
          quantityNeeded: 23,
          unit: null,
          inCart: true,
          name: "baking soda",
          category: "BAKING_SUPPLIES",
          defaultUnit: null,
          id: "HOgnJYGaUAuyHGscgLvg",
          catalogId: "1cBER9Mj8fBKW8BGtews",
        },
        {
          quantityNeeded: 3,
          unit: null,
          inCart: null,
          name: "avocado",
          category: "PRODUCE",
          defaultUnit: null,
          id: "MwOhbCxxFjpzL92ylyGC",
          catalogId: "cVACp992BGJL3Pu5hNK7",
        },
        {
          quantityNeeded: 3,
          unit: null,
          inCart: null,
          name: "blueberries",
          category: "PRODUCE",
          defaultUnit: null,
          id: "PkFLdxPi7qoUwJzBZs93",
          catalogId: "Lw3J99XpF3OOUsTJbnLh",
        },
        {
          quantityNeeded: 1,
          unit: null,
          inCart: null,
          name: "cumin",
          category: "SPICES",
          defaultUnit: "",
          id: "R9VIx6Wa7UMpyAaFXp0w",
          catalogId: "Aoz1zxEsr2rpCGboTPGs",
        },
        {
          quantityNeeded: 3,
          unit: null,
          inCart: null,
          name: "strawberries",
          category: "PRODUCE",
          defaultUnit: "",
          id: "WHWulmct1oFxI313Xkfg",
          catalogId: "bVjnAMxfniankQFncjeb",
        },
        {
          quantityNeeded: 1,
          unit: "PACKAGE",
          inCart: true,
          name: "chocolate chips",
          category: "BAKING_SUPPLIES",
          defaultUnit: null,
          id: "Y6mlNpVJ3fkT9minwj2n",
          catalogId: "AugbR128XIY95AI2Gxqp",
        },
        {
          quantityNeeded: 2,
          unit: "POUND",
          inCart: null,
          name: "ground beef",
          category: "MEAT",
          defaultUnit: "POUND",
          id: "Z2j2Bk2pZa4yElOwV4QY",
          catalogId: "53eOawTxFwPQshJskTPV",
        },
        {
          quantityNeeded: 1,
          unit: null,
          inCart: null,
          name: "carrot",
          category: "PRODUCE",
          defaultUnit: null,
          id: "fFc2d1KXM4IQ7SsYTNgM",
          catalogId: "3xlep01NAlqXN7hFvAAo",
        },
        {
          quantityNeeded: 2,
          unit: "POUND",
          inCart: null,
          name: "chicken breast",
          category: "MEAT",
          defaultUnit: null,
          id: "j0FZJF4KtAeLNgD1vSGZ",
          catalogId: "u5Vj7AdvP9PXvfoaWi2D",
        },
        {
          quantityNeeded: 1,
          unit: "OZ",
          inCart: null,
          name: "cinnamon",
          category: "SPICES",
          defaultUnit: null,
          id: "kLw6fhJKnGNpjS0yf433",
          catalogId: "hcJOx4KrCUOVtJZE63CE",
        },
        {
          quantityNeeded: 1,
          unit: null,
          inCart: true,
          name: "light brown sugar",
          category: "BAKING_SUPPLIES",
          defaultUnit: null,
          id: "s0JoaaUJvkTk6lcK3Lbs",
          catalogId: "8NiJ7iJpyLYHSSmHGsHl",
        },
        {
          quantityNeeded: 1,
          unit: null,
          inCart: true,
          name: "berry LaCroix",
          category: "BEVERAGES",
          defaultUnit: null,
          id: "zHI93KDMjdchUJ8m9Tzp",
          catalogId: "f7dyjnjzWQ8Ux3FA5S5u",
        },
        {
          quantityNeeded: 1,
          unit: null,
          inCart: null,
          name: "sourdough bread",
          category: "BAKED_GOODS",
          defaultUnit: "",
          id: "zIlZGqgAc8Z6g1beAAzA",
          catalogId: "ia7C2e22ENpLIW9NnpDu",
        },
      ],
      createdAt: "2022-07-03T23:42:16.153Z",
      updatedAt: "2022-07-03T23:42:16.153Z",
    },
  },
};

export const mockAddItemToCart = {
  data: {
    addItemToCart: {
      code: 200,
      success: true,
      message: "Item successfully added to cart",
      item: {
        id: "HocYjWv2H57PG86dNlYD",
        name: "banana",
        category: "PRODUCE",
        defaultUnit: "",
        quantityNeeded: 3,
        unit: null,
        inCart: true,
      },
    },
  },
};

export const mockAddItemToList = {
  data: {
    addItemToList: {
      code: 200,
      success: true,
      message: "Item successfully added to list",
      item: {
        itemId: "3xlep01NAlqXN7hFvAAo",
        quantityNeeded: 1,
        unit: null,
        inCart: null,
      },
    },
  },
};
