export const shoppingCategoriesMap = {
  BAKED_GOODS: "Baked Goods",
  BAKING_SUPPLIES: "Baking Supplies",
  BEVERAGES: "Beverages",
  CANNED_GOODS: "Canned Goods",
  CEREAL: "Cereal",
  CLEANING_SUPPLIES: "Cleaning Supplies",
  COFFEE_AND_TEA: "Coffee & Tea",
  CONDIMENTS: "Condiments",
  DAIRY: "Dairy",
  DELI_MEATS: "Deli Meats",
  DRY_GOODS: "Dry Goods",
  FROZEN_FOODS: "Frozen Foods",
  HEALTH_AND_BEAUTY: "Health & Beauty",
  HOME_IMPROVEMENT: "Home Improvment",
  MEAT: "Meat",
  PAPER_PRODUCTS: "Paper Products",
  PET_SUPPLIES: "Pet Supplies",
  PREPARED_FOODS: "Prepared Foods",
  PRODUCE: "Produce",
  SNACKS: "Snacks",
  SPICES: "Spices",
  VITAMINS_AND_SUPPLIMENTS: "Vitamins & Suppliments",
};
